// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScadAgent.Infrastructure.Persistence;

#nullable disable

namespace ScadAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScadAgentDbContext))]
    [Migration("20260625203829_AddSessionContextSummary")]
    partial class AddSessionContextSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ScadAgent.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Intent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IterationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.DesignIteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewArtifactPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScadContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StlArtifactPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Version")
                        .IsUnique();

                    b.ToTable("Iterations");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.DesignSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContextSummarizedThroughMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentIterationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentIterationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("ScadAgent.Domain.Entities.DesignIteration", "Iteration")
                        .WithMany()
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScadAgent.Domain.Entities.DesignSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.DesignIteration", b =>
                {
                    b.HasOne("ScadAgent.Domain.Entities.DesignSession", "Session")
                        .WithMany("Iterations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.DesignSession", b =>
                {
                    b.HasOne("ScadAgent.Domain.Entities.DesignIteration", "CurrentIteration")
                        .WithMany()
                        .HasForeignKey("CurrentIterationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentIteration");
                });

            modelBuilder.Entity("ScadAgent.Domain.Entities.DesignSession", b =>
                {
                    b.Navigation("Iterations");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
